/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sintia1;

/**
 *
 * @author LAB-MM
 */
public class formstudent extends javax.swing.JFrame {

    /**
     * Creates new form formstudent
     */
    public formstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatematika = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBing = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtImuPengetahuan = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 26, 14);

        txtNama.setText("jTextField1");
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama);
        txtNama.setBounds(120, 10, 250, 20);

        jLabel2.setText("alamat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 32, 14);

        txtAlamat.setText("jTextField2");
        jPanel1.add(txtAlamat);
        txtAlamat.setBounds(120, 40, 250, 20);

        jLabel3.setText("umur");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 24, 14);

        txtUmur.setText("jTextField3");
        jPanel1.add(txtUmur);
        txtUmur.setBounds(120, 70, 250, 20);

        jLabel4.setText("matematika");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 55, 14);

        txtMatematika.setText("jTextField4");
        jPanel1.add(txtMatematika);
        txtMatematika.setBounds(120, 110, 250, 20);

        jLabel5.setText("B.iggris");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 35, 14);

        txtBing.setText("jTextField5");
        jPanel1.add(txtBing);
        txtBing.setBounds(120, 150, 250, 20);

        jLabel6.setText("ilmu pengetahuan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 190, 34, 14);

        txtImuPengetahuan.setText("jTextField6");
        jPanel1.add(txtImuPengetahuan);
        txtImuPengetahuan.setBounds(120, 190, 250, 20);

        btnProses.setText("proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        jPanel1.add(btnProses);
        btnProses.setBounds(10, 240, 65, 23);

        jLabel7.setText("rata-rata");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 280, 44, 14);

        txtHasil.setText("jTextField7");
        jPanel1.add(txtHasil);
        txtHasil.setBounds(120, 270, 250, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        StudentRecord student = new StudentRecord();
        student.setName(txtNama.getText());
        student.setAddress(txtAlamat.getText());
        student.setAge(Integer.parseInt(txtUmur.getText()));
        student.setmathGrade(Double.parseDouble(txtMatematika.getText()));
         student.setenglishGrade(Double.parseDouble(txtBing.getText()));
           student.setscienceGrade(Double.parseDouble(txtImuPengetahuan.getText()));
           txtHasil.setText(String.valueOf(student.getaverage()));
        
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBing;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtImuPengetahuan;
    private javax.swing.JTextField txtMatematika;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
